- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app_setup

- name: node js disable existing 
  ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

- name: node js 18 install
  ansible.builtin.dnf:
    name: nodejs
    state: present


- name: install npm
  ansible.builtin.command: npm install
  args:
    chdir: /app

- name: systemd changes catalogue service
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: systemd reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: mongod repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: mongod installation
  ansible.builtin.package:
    name: mongodb-org-shell
    state: present

- name: get the categories count
  ansible.builtin.command:  mongo --host mongodb.roboshop.store --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
  register: product_count

# - name: print the count
#   ansible.builtin.debug:
#     msg: "product count: {{product_count}}"

- name: load catalogue data
  ansible.builtin.command: mongo --host mongodb.roboshop.store < /app/schema/catalogue.js
  when: product_count.stdout == "0" # keep double quotes

- name: start and enable catalogue
  ansible.builtin.service:
    name: catalogue
    state: restarted
    enabled: yes