- name: mysql client installation
  ansible.builtin.dnf:
    name: mysql
    state: present

- name: check cities schema exists or not
  ansible.builtin.command: mysql -h {{MYSQL_HOST}} -uroot -pRoboshop@1 -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cities'" 
  register: schema

- name: load cities data
  ansible.builtin.shell: "mysql -h {{MYSQL_HOST}} -uroot -pRoboshop@1  < /app/db/schema.sql"
  when: schema.stdout != "1"

- name: load cities data
  ansible.builtin.shell: "mysql -h {{MYSQL_HOST}} -uroot -pRoboshop@1  < /app/db/app-user.sql"

- name: load cities data
  ansible.builtin.shell: "mysql -h {{MYSQL_HOST}} -uroot -pRoboshop@1  < /app/db/master-data.sql"
  